#!/bin/bash
# Adiciona o R ao apt e instala
#
# Instructions:
# sudo chmod 700 InstallR.sh
# ./InstallR.sh

# Instala o R 3.5 a partir do ppa do Michael Rutter: https://launchpad.net/~marutter/+archive/ubuntu/rrutter3.5

sudo add-apt-repository ppa:marutter/rrutter3.5
sudo apt-get update

gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
gpg -a --export E084DAB9 | sudo apt-key add -
  
sudo apt-get update
sudo apt-get install -y r-base r-base-dev 
sudo R CMD javareconf 

## Instala a última versão do rstudio-server
sudo apt-get install gdebi-core
wget https://download2.rstudio.org/rstudio-server-1.1.453-amd64.deb
sudo gdebi rstudio-server-1.1.453-amd64.deb

## Instala a versão mais recente do Shiny-server
sudo su - \
-c "R -e \"install.packages('shiny', repos='https://cran.rstudio.com/')\""

wget https://download3.rstudio.org/ubuntu-14.04/x86_64/shiny-server-1.5.7.907-amd64.deb
sudo gdebi shiny-server-1.5.7.907-amd64.deb
